import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CHAIN } from "@tonconnect/protocol";

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { TonConnectUIProvider } from "@tonconnect/ui-react";
import { useTonConnect } from "@/hooks";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const queryClient = new QueryClient({
  defaultOptions: { queries: { refetchOnWindowFocus: false } },
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manifestUrl =
  "https://raw.githubusercontent.com/ton-community/tutorials/main/03-client/test/public/tonconnect-manifest.json";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const { network } = useTonConnect();

  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {/* <TonConnectUIProvider manifestUrl={manifestUrl}>
          <QueryClientProvider client={queryClient}>
            {children}
          </QueryClientProvider>
        </TonConnectUIProvider> */}
      </body>
    </html>
  );
}






